/**
 * Demo data seed (#36) — `npm run seed`
 *
 * Inserts a realistic showcase dataset (generated by scripts/demo-data.mjs)
 * for the demo user demo@queuti.com / demo1234 (upserted; password
 * re-hashed on every run so it always works).
 *
 * Idempotent: every seeded doc carries `demo: true`; on start we delete ONLY
 * docs flagged `demo` for this user, then re-insert fresh. Real user data is
 * never touched. Run any time — safe.
 *
 * Requires MONGO_URI (reads .env.local if present, else env).
 */

import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { MongoClient } from "mongodb";
import bcrypt from "bcryptjs";
import { buildDemoDataset, DEMO_EMAIL, DEMO_PASSWORD } from "./demo-data.mjs";

// ---- env: prefer real env, fall back to .env.local (parsed manually so the
// ---- script has zero extra deps beyond the app's own mongodb/bcryptjs).
const __dirname = dirname(fileURLToPath(import.meta.url));
const envLocal = resolve(__dirname, "..", ".env.local");
function loadEnvLocal() {
  if (!existsSync(envLocal)) return {};
  const out = {};
  for (const raw of readFileSync(envLocal, "utf8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}
const uri = process.env.MONGO_URI || loadEnvLocal().MONGO_URI;
if (!uri) {
  console.error("❌ MONGO_URI is not set. Add it to .env.local (gitignored) or export it, then re-run: npm run seed");
  process.exit(1);
}

const DB_NAME = process.env.MONGODB_DB || "queuti";

async function main() {
  const client = new MongoClient(uri, { maxPoolSize: 5, serverSelectionTimeoutMS: 10000 });
  await client.connect();
  const db = client.db(DB_NAME);
  const users = db.collection("users");
  const apps = db.collection("applications");
  const events = db.collection("events");
  const companies = db.collection("companies");
  const contacts = db.collection("contacts");

  // 1. Demo user (upsert).
  const now = new Date();
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10);
  let user = await users.findOne({ email: DEMO_EMAIL });
  if (user) {
    await users.updateOne({ _id: user._id }, { $set: { passwordHash, updatedAt: now, demo: true } });
  } else {
    const res = await users.insertOne({
      email: DEMO_EMAIL, passwordHash, name: "Demo Candidate",
      demo: true, createdAt: now, updatedAt: now,
    });
    user = { _id: res.insertedId, email: DEMO_EMAIL, passwordHash, name: "Demo Candidate", createdAt: now, updatedAt: now };
  }
  const uid = user._id;

  // 2. Idempotent wipe: delete ONLY demo-flagged docs for this user.
  const [cApp, cEvt, cCmp, cCtc] = await Promise.all([
    apps.deleteMany({ userId: uid, demo: true }),
    events.deleteMany({ userId: uid, demo: true }),
    companies.deleteMany({ userId: uid, demo: true }),
    contacts.deleteMany({ userId: uid, demo: true }),
  ]);
  console.log(`🧹 Wiped previous demo data: ${cApp.deletedCount} apps, ${cEvt.deletedCount} events, ${cCmp.deletedCount} companies, ${cCtc.deletedCount} contacts`);

  // 3. Generate dataset (pure) and insert companies first so apps/contacts
  //    can reference real company ids.
  const data = buildDemoDataset({ userId: uid });
  const companyIds = [];
  for (const c of data.companies) {
    const res = await companies.insertOne(c);
    companyIds.push(res.insertedId);
  }
  for (const c of data.contacts) {
    await contacts.insertOne({ ...c, companyId: companyIds[c.companyId] });
  }

  const inserted = await apps.insertMany(
    data.applications.map((a) => ({ ...a, companyId: companyIds[a.companyId] }))
  );
  const ids = Object.values(inserted.insertedIds);
  let evtCount = 0;
  for (let i = 0; i < data.applications.length; i++) {
    const aid = ids[i];
    for (const ev of data.events.filter((e) => e.applicationId === data.applications[i]._id)) {
      await events.insertOne({ ...ev, applicationId: aid });
      evtCount++;
    }
  }

  const byStatus = data.statuses.reduce((acc, s) => {
    acc[s] = (acc[s] || 0) + 1;
    return acc;
  }, {});
  console.log(`✅ Seeded ${data.applications.length} applications (${Object.entries(byStatus).map(([s, n]) => `${s}: ${n}`).join(", ")})`);
  console.log(`✅ Seeded ${evtCount} timeline events, ${data.companies.length} companies, ${data.contacts.length} contacts`);
  console.log(`\n👤 Demo login: ${DEMO_EMAIL} / ${DEMO_PASSWORD}`);
  console.log("Open /dashboard — kanban, ledger, analytics, upcoming interviews and market panel are populated.");
  await client.close();
}

main().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});